{% set name = "rdma-core" %}
{% set version = "56.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/linux-rdma/rdma-core/archive/v{{ version }}.tar.gz
  sha256: 0ebac5735bc38cafeba28a3124566b56606f11a8462c794411858efa7b407be0
  patches:
    - 0001-Remove-assertions-on-longer-than-sockaddr_un.sun_pat.patch

build:
  number: 1
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage("rdma-core", max_pin=None) }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - pandoc
    - pkgconfig
    - python
    - docutils
  host:
    - libnl
    - libsystemd
    - libudev

test:
  commands:
    - test -f "${PREFIX}/bin/ibv_devices"
    # Test `ibv_devices` when building natively
    - ${PREFIX}/bin/ibv_devices            # [build_platform == target_platform]

about:
  home: https://github.com/linux-rdma/rdma-core
  license: Linux-OpenIB
  license_family: BSD
  license_file: LICENSE.txt
  summary: RDMA Core Userspace Libraries and Daemons
  doc_url: https://github.com/linux-rdma/rdma-core
  dev_url: https://github.com/linux-rdma/rdma-core

extra:
  recipe-maintainers:
    - pentschev
