{% set name = "rdma-core" %}
{% set version = "30.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/linux-rdma/rdma-core/archive/v{{ version }}.tar.gz
  sha256: 93c7e9ea913018334b242c594affec261e185a59e176cb71a78c5b5cfce03d7c
  patches:
    - 0001-Remove-assertions-on-longer-than-sockaddr_un.sun_pat.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage("rdma-core") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ cdt("libnl3-devel") }}
    - {{ cdt("systemd-devel") }}
    - sysroot_linux-64 2.17  # [linux64]
    - cmake
    - ninja
    - libudev
    - libsystemd
    - pandoc

test:
  commands:
    - test -f "${PREFIX}/bin/ibv_devices"
    - ${PREFIX}/bin/ibv_devices

about:
  home: https://github.com/linux-rdma/rdma-core
  license: Linux-OpenIB
  license_family: BSD
  license_file: LICENSE.txt
  summary: RDMA Core Userspace Libraries and Daemons
  doc_url: https://github.com/linux-rdma/rdma-core
  dev_url: https://github.com/linux-rdma/rdma-core

extra:
  recipe-maintainers:
    - pentschev
